// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD58tsrHrXLkXQ7P4KN3E1FIHIb6gzEGwc',
    appId: '1:366055150946:web:8eb9771e128364c4e9483b',
    messagingSenderId: '366055150946',
    projectId: 'rent-eazy',
    authDomain: 'rent-eazy.firebaseapp.com',
    storageBucket: 'rent-eazy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVN3ofmIgk5JWgaV7o06h3sMJNwhrQ9mg',
    appId: '1:366055150946:android:d63d68d03ae48396e9483b',
    messagingSenderId: '366055150946',
    projectId: 'rent-eazy',
    storageBucket: 'rent-eazy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClM5c28Cc7Hb8K3Kd-Xf7BheEMI2pvWwk',
    appId: '1:366055150946:ios:db91f4fecd36d62ae9483b',
    messagingSenderId: '366055150946',
    projectId: 'rent-eazy',
    storageBucket: 'rent-eazy.appspot.com',
    iosBundleId: 'com.example.rentEasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClM5c28Cc7Hb8K3Kd-Xf7BheEMI2pvWwk',
    appId: '1:366055150946:ios:db91f4fecd36d62ae9483b',
    messagingSenderId: '366055150946',
    projectId: 'rent-eazy',
    storageBucket: 'rent-eazy.appspot.com',
    iosBundleId: 'com.example.rentEasy',
  );
}
